# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nightly CITGM

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 */8 * * *'
  push:
    branches: 
      - master

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [windows-latest, macos-latest, ubuntu-16.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
